# Generated by Django 5.0.1 on 2024-02-05 00:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='is_returned_alive',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='mission_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='objective',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 5, 0, 59, 17, 152296, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
