# Generated by Django 4.2.7 on 2024-01-09 16:19

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Astronauts',
            fields=[
                ('astronaut_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=30)),
                ('background', models.CharField(max_length=2000)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('sex', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('is_suspended', models.BooleanField(blank=True, null=True)),
            ],
            options={
                'db_table': 'astronauts',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('login', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('is_moderator', models.BooleanField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=70, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Flights',
            fields=[
                ('flight_id', models.AutoField(primary_key=True, serialize=False)),
                ('mission_name', models.CharField(max_length=100)),
                ('destination', models.CharField(blank=True, max_length=100, null=True)),
                ('objective', models.CharField(blank=True, max_length=1000, null=True)),
                ('flight_status', models.IntegerField(choices=[(1, 'Черновик'), (2, 'Удален'), (3, 'Сформирован'), (4, 'Завершен'), (5, 'Отклонен')], default=1)),
                ('date_of_creation', models.DateTimeField(default=datetime.datetime(2024, 1, 9, 16, 19, 28, 580530, tzinfo=datetime.timezone.utc), verbose_name='Дата создания')),
                ('date_of_formation', models.DateTimeField(blank=True, null=True, verbose_name='Дата формирования')),
                ('date_of_completion', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flights_moderator_set', to='OrionFlights.users')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flights_user_set', to='OrionFlights.users')),
            ],
            options={
                'db_table': 'flights',
            },
        ),
        migrations.CreateModel(
            name='AstronautFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_captain', models.BooleanField(blank=True, null=True)),
                ('astronaut', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OrionFlights.astronauts')),
                ('flight', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OrionFlights.flights')),
            ],
            options={
                'db_table': 'astronaut_flight',
            },
        ),
    ]
