# Generated by Django 4.2.7 on 2024-01-09 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrionFlights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astronauts',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flights',
            name='date_of_creation',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 9, 17, 9, 57, 132542, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
